### ISSUE TITLE
werid bug

### ISSUE THREAD

**Issue by cWorksLLC** [G1aD05/scratchcon#11]
so i wrote a program that takes the message count of a user and returned this:
`Traceback (most recent call last):
  File "C:\Users\USER\Desktop\mescount.py", line 6, in <module>
    msg = user.get_message_count()
  File "C:\Users\USER\AppData\Local\Programs\Python\Python313\Lib\site-packages\scratchcon\user.py", line 17, in get_message_count
    response = requests.get(f"{public.user_link}/messages/count")
  File "C:\Users\USER\AppData\Local\Programs\Python\Python313\Lib\site-packages\requests\api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
  File "C:\Users\USER\AppData\Local\Programs\Python\Python313\Lib\site-packages\requests\api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\USER\AppData\Local\Programs\Python\Python313\Lib\site-packages\requests\sessions.py", line 575, in request
    prep = self.prepare_request(req)
  File "C:\Users\USER\AppData\Local\Programs\Python\Python313\Lib\site-packages\requests\sessions.py", line 484, in prepare_request
    p.prepare(
    ~~~~~~~~~^
        method=request.method.upper(),
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<10 lines>...
        hooks=merge_hooks(request.hooks, self.hooks),
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\USER\AppData\Local\Programs\Python\Python313\Lib\site-packages\requests\models.py", line 367, in prepare
    self.prepare_url(url, params)
    ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "C:\Users\USER\AppData\Local\Programs\Python\Python313\Lib\site-packages\requests\models.py", line 438, in prepare_url
    raise MissingSchema(
    ...<2 lines>...
    )
requests.exceptions.MissingSchema: Invalid URL 'None/messages/count': No scheme supplied. Perhaps you meant https://None/messages/count?`
(replaced all mentions of my pc name with USER) you know any fixes?

**Comment by G1aD05** [comment]
Did you forget to add https:// at the start of the link?

**Comment by G1aD05** [comment]
Also why is it showing "None" in the URL?

**Comment by webbrowser11** [comment]
if you do that it should fix it.
